In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline

In [ ]:
global_df = pd.read_csv('/content/global_climate_health_impact_tracker_2015_2025..csv')

In [ ]:
global_df

,record_id,country_code,country_name,region,income_level,date,year,month,week,latitude,...,air_quality_index,respiratory_disease_rate,cardio_mortality_rate,vector_disease_risk_score,waterborne_disease_incidents,heat_related_admissions,healthcare_access_index,gdp_per_capita_usd,mental_health_index,food_security_index
0,1,USA,United States,North America,High,2015-01-04,2015,1,1,37.09,...,82.0,69.4,31.5,6.6,16.2,1.4,77.3,63627.0,71.2,90.2
1,2,USA,United States,North America,High,2015-01-11,2015,1,2,37.09,...,6.0,70.0,26.3,5.2,11.4,0.0,83.6,63627.0,70.6,94.0
2,3,USA,United States,North America,High,2015-01-18,2015,1,3,37.09,...,137.0,66.9,33.4,1.3,19.5,0.0,84.7,63627.0,63.4,100.0
3,4,USA,United States,North America,High,2015-01-25,2015,1,4,37.09,...,-3.0,47.0,35.0,6.0,9.7,9.0,84.3,63627.0,68.1,96.4
4,5,USA,United States,North America,High,2015-02-01,2015,2,5,37.09,...,48.0,61.3,28.3,1.4,22.6,27.3,83.6,63733.0,69.1,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14095,14096,COL,Colombia,South America,Upper-Middle,2025-09-21,2025,9,38,4.57,...,137.0,63.2,20.2,0.7,21.9,0.0,64.5,10432.0,74.3,100.0
14096,14097,COL,Colombia,South America,Upper-Middle,2025-09-28,2025,9,39,4.57,...,160.0,83.8,37.7,6.2,19.8,0.0,71.8,10432.0,62.3,95.8
14097,14098,COL,Colombia,South America,Upper-Middle,2025-10-05,2025,10,40,4.57,...,92.0,79.1,31.5,4.1,16.2,0.0,71.9,10446.0,71.0,89.4
14098,14099,COL,Colombia,South America,Upper-Middle,2025-10-12,2025,10,41,4.57,...,16.0,56.5,35.7,11.2,18.7,0.0,68.4,10446.0,59.8,96.7
14099,14100,COL,Colombia,South America,Upper-Middle,2025-10-19,2025,10,42,4.57,...,48.0,58.8,28.5,1.6,15.9,0.0,74.0,10446.0,61.0,100.0

In [ ]:
global_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14100 entries, 0 to 14099
Data columns (total 30 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   record_id                     14100 non-null  int64
 1   country_code                  14100 non-null  object
 2   country_name                  14100 non-null  object
 3   region                        14100 non-null  object
 4   income_level                  14100 non-null  object
 5   date                          14100 non-null  object
 6   year                          14100 non-null  int64
 7   month                         14100 non-null  int64
 8   week                          14100 non-null  int64
 9   latitude                      14100 non-null  float64
 10  longitude                     14100 non-null  float64
 11  population_millions           14100 non-null  int64
 12  temperature_celsius           14100 non-null  float64
 13  temp_anomaly_celsius          14100 non-null  float64
 14  precipitation_mm              14100 non-null  float64
 15  heat_wave_days                14100 non-null  int64
 16  drought_indicator             14100 non-null  int64
 17  flood_indicator               14100 non-null  int64
 18  extreme_weather_events        14100 non-null  int64
 19  pm25_ugm3                     14100 non-null  float64
 20  air_quality_index             14100 non-null  float64
 21  respiratory_disease_rate      14100 non-null  float64
 22  cardio_mortality_rate         14100 non-null  float64
 23  vector_disease_risk_score     14100 non-null  float64
 24  waterborne_disease_incidents  14100 non-null  float64
 25  heat_related_admissions       14100 non-null  float64
 26  healthcare_access_index       14100 non-null  float64
 27  gdp_per_capita_usd            14100 non-null  float64
 28  mental_health_index           14100 non-null  float64
 29  food_security_index           14100 non-null  float64
dtypes: float64(16), int64(9), object(5)
memory usage: 3.2+ MB

In [ ]:
global_df.describe()

,record_id,year,month,week,latitude,longitude,population_millions,temperature_celsius,temp_anomaly_celsius,precipitation_mm,...,air_quality_index,respiratory_disease_rate,cardio_mortality_rate,vector_disease_risk_score,waterborne_disease_incidents,heat_related_admissions,healthcare_access_index,gdp_per_capita_usd,mental_health_index,food_security_index
count,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,...,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000,14100.000000
mean,7050.500000,2019.911348,6.437943,26.221631,18.905200,27.349600,217.440000,8.607113,0.120879,81.149440,...,98.750071,70.016872,30.758596,12.096277,22.172965,6.880794,64.875674,26331.105887,69.874638,93.295780
std,4070.463733,3.118225,3.421173,14.930110,25.730498,76.062029,355.979373,11.289938,0.506365,40.821462,...,59.143284,15.223261,5.605436,17.146545,6.609017,9.498276,18.230095,26329.114275,5.025983,6.295667
min,1.000000,2015.000000,1.000000,1.000000,-38.410000,-106.340000,26.000000,-20.740000,-1.760000,0.000000,...,-52.000000,21.200000,8.000000,0.000000,0.000000,0.000000,27.900000,1565.000000,47.700000,62.200000
25%,3525.750000,2017.000000,3.000000,13.000000,4.570000,-3.740000,60.000000,0.257500,-0.220000,51.500000,...,54.000000,59.200000,27.000000,3.500000,17.800000,0.000000,47.100000,3548.000000,66.500000,88.800000
50%,7050.500000,2020.000000,6.000000,26.000000,23.630000,22.930000,98.000000,8.630000,0.120000,80.900000,...,93.000000,69.600000,30.800000,5.800000,22.100000,0.600000,66.600000,13941.000000,70.000000,94.400000
75%,10575.250000,2023.000000,9.000000,39.000000,37.090000,100.990000,206.000000,16.850000,0.460000,110.600000,...,142.000000,80.500000,34.500000,8.900000,26.400000,12.300000,81.500000,50206.500000,73.300000,99.700000
max,14100.000000,2025.000000,12.000000,53.000000,56.130000,138.250000,1411.000000,38.330000,2.120000,222.900000,...,302.000000,131.800000,51.100000,100.000000,63.000000,59.600000,102.000000,78630.000000,88.700000,100.000000